#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "dotfile: $*"
    fi
  } >&2
  exit 1
}

DOTFILES_DIR="${HOME}/.dotfiles"
export DOTFILES_DIR

shopt -u nullglob

command="$1"
case "$command" in
"" )
  { dotfile-help
  } | abort
  ;;
-h | --help )
  exec dotfile-help
  ;;
* )
  command_path="$(command -v "dotfile-$command" || true)"
  [ -n "$command_path" ] || abort "no such command \`$command'"

  shift 1
  if [ "$1" = --help ]; then
    exec dotfile-help "$command"
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
