#!/usr/bin/env bash

set -e
[ -n "$DOTFILE_DEBUG" ] && set -x

git_status_count() {
  git status -s | wc -l | sed -e 's/^  *//g' | sed -e 's/  *$//g';
}

git_status_file_name() {
  git status -s | awk '{print $2}';
}

cd "$DOTFILES_DIR"

if [ -z "$1" ]; then 
  case "$(git_status_count)" in
  '0')
    echo "nothing to commit, working directory clean"
    ;;
  '1')
    git add -A
    git commit -m "Update $(git_status_file_name)"
    ;;
  *)
    git add -A
    git commit -m "Update dotfiles"
    ;;
  esac
else
  git commit "$@"
fi
