#!/usr/bin/env bash

set -e
[ -n "$DOTFILE_DEBUG" ] && set -x

command_path() {
  local command="$1"
  command -v dotfile-"$command" || true
}

if [ -z "$1" ] || [ "$1" == "dotfile" ]; then
  echo "Usage: dotfile <command> [<args>]"
  echo
  echo "Some useful dotfile commands are:"
  echo "   status   Show the working tree status"
  echo "   commit   Record changes to the repository."
  echo "   push     Update remote refs along with associated objects"
  echo
  echo "See \`dotfile help <command>' for information on a specific command."
else
  command="$1"
  if [ -n "$(command_path "$command")" ]; then
    echo "TODO: dotfile help $command"
  else
    echo "dotfile: no such command \`$command'" >&2
    exit 1
  fi
fi
