[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'ruby-matchit'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neocomplcache-rsense'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cespare/vim-toml'
