if &compatible
  setglobal nocompatible
endif

function! s:source_rc(path) abort
  execute 'source' fnameescape(expand('~/.vim/rc/' . a:path))
endfunction

nnoremap ;  <Nop>
xnoremap ;  <Nop>
nnoremap m  <Nop>
xnoremap m  <Nop>
nnoremap ,  <Nop>
xnoremap ,  <Nop>

setglobal runtimepath^=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle/'))

if neobundle#load_cache(
      \ expand('<sfile>'),
      \ '~/.vim/rc/neobundle.toml',
      \ '~/.vim/rc/neobundlelazy.toml')
  NeoBundleFetch 'Shougo/neobundle.vim'

  call neobundle#load_toml(
        \ '~/.vim/rc/neobundle.toml')
  call neobundle#load_toml(
        \ '~/.vim/rc/neobundlelazy.toml', {'lazy' : 1})

  NeoBundleSaveCache
endif

call s:source_rc('plugins.rc.vim')

call neobundle#end()

filetype plugin indent on

syntax enable

if !has('vim_starting')
  NeoBundleCheck
endif

setglobal ambiwidth=double
setglobal autoindent
setglobal backspace=2
setglobal clipboard+=unnamed
setglobal encoding=utf-8
setglobal expandtab
setglobal hlsearch
setglobal ignorecase
setglobal laststatus=2
setglobal nobackup
setglobal number
setglobal shiftwidth=2
setglobal smartcase
setglobal softtabstop=2
setglobal wildmenu

hi Comment ctermfg=69

if filereadable(expand($HOME.'/.vimrc.local'))
  execute 'source' expand($HOME.'/.vimrc.local')
endif
