if &compatible
  set nocompatible
endif

function! s:source_rc(path) abort
  execute 'source' fnameescape(expand('~/.vim/rc/' . a:path))
endfunction

nnoremap ;  <Nop>
xnoremap ;  <Nop>
nnoremap m  <Nop>
xnoremap m  <Nop>
nnoremap ,  <Nop>
xnoremap ,  <Nop>

set runtimepath^=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle/'))

if neobundle#load_cache(
      \ expand('<sfile>'),
      \ '~/.vim/rc/neobundle.toml',
      \ '~/.vim/rc/neobundlelazy.toml')
  NeoBundleFetch 'Shougo/neobundle.vim'

  call neobundle#load_toml(
        \ '~/.vim/rc/neobundle.toml')
  call neobundle#load_toml(
        \ '~/.vim/rc/neobundlelazy.toml', {'lazy' : 1})

  NeoBundleSaveCache
endif

call s:source_rc('plugins.rc.vim')

call neobundle#end()

filetype plugin indent on

syntax enable

if !has('vim_starting')
  NeoBundleCheck
endif

set ambiwidth=double
set autoindent
set backspace=2
set clipboard+=unnamed
set cursorline
set encoding=utf-8
set expandtab
set hlsearch
set ignorecase
set laststatus=2
set nobackup
set number
set shiftwidth=2
set smartcase
set softtabstop=2
set wildmenu

hi Comment ctermfg=69

nnoremap <ESC><ESC> :nohlsearch<CR>:match<CR>

if filereadable(expand($HOME.'/.vimrc.local'))
  execute 'source' expand($HOME.'/.vimrc.local')
endif
