#!/usr/bin/env bash

error() {
  echo "$@" 1>&2
}

abort() {
  echo "$@" 1>&2
  exit 1
}

is_exists() {
  type "$1" >/dev/null 2>&1
  return $?
}

if [ -z "${DOTFILES_HOME:-}" ]; then
  DOTFILES_HOME=~/.dotfiles; export DOTFILES_HOME
fi

declare -rx DOTFILES_GITHUB='https://github.com/ojiry/dotfiles.git'

dotfiles_download() {
  if [ -d "$DOTFILES_HOME" ]; then
    echo "$DOTFILES_HOME: already exists"
    exit 1
  fi
  if is_exists "git"; then
    git clone --recursive "$DOTFILES_GITHUB" "$DOTFILES_HOME"

  elif is_exists "curl" || is_exists "wget"; then
    local tarball='https://github.com/ojiry/dotfiles/archive/master.tar.gz'
    if is_exists "curl"; then
      curl -L "$tarball"
    elif is_exists "wget"; then
      wget -O - "$tarball"
    fi | tar xvz
    if [ ! -d dotfiles-master ]; then
      echo "dotfiles-master: not found"
      exit 1
    fi
    command mv -f dotfiles-master "$DOTFILES_HOME"
  else
    echo "curl or wget required"
    exit 1
  fi
}

dotfiles_deploy() {
  if [ ! -d $DOTFILES_HOME ]; then
    echo "$DOTFILES_HOME: not found"
    exit 1
  fi

  cd "$DOTFILES_HOME"
  make install
}

# A script for the file named "install"
dotfiles_install() {
  # 1. Download the repository
  # ==> downloading
  #
  # Priority: git > curl > wget
  dotfiles_download &&

    # 2. Deploy dotfiles to your home directory
  # ==> deploying
  dotfiles_deploy
}

dotfiles_install "$@"
