#!/usr/bin/env bash

if [ -z "${DOTFILES_HOME:-}" ]; then
  DOTFILES_HOME=~/.dotfiles; export DOTFILES_HOME
fi

declare -rx DOTFILES_GITHUB='https://github.com/ojiry/dotfiles.git'

if [ -d "$DOTFILES_HOME" ]; then
  echo "$DOTFILES_HOME: already exists."
  exit 1
fi

if ! type git >/dev/null 2>&1; then
  echo "git: command not found."
  exit 1
fi

git clone --recursive "$DOTFILES_GITHUB" "$DOTFILES_HOME"

if [ ! -d $DOTFILES_HOME ]; then
  echo "$DOTFILES_HOME: not found."
  exit 1
fi

cd "$DOTFILES_HOME"
make install

echo "Installation has been completed."
