#!/usr/bin/env bash

if [ -z "${DOTFILES_HOME:-}" ]; then
  DOTFILES_HOME=~/.dotfiles; export DOTFILES_HOME
fi

declare -rx DOTFILES_GITHUB='https://github.com/ojiry/dotfiles.git'

if [ -d "$DOTFILES_HOME" ]; then
  echo "$DOTFILES_HOME: already exists."
  exit 1
fi

if ! type git >/dev/null 2>&1; then
  echo "git: command not found."
  exit 1
fi

git clone --recursive "$DOTFILES_GITHUB" "$DOTFILES_HOME"

if [ ! -d $DOTFILES_HOME ]; then
  echo "$DOTFILES_HOME: not found."
  exit 1
fi

[ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
[ ! -d "${HOME}/.config/dein" ] && mkdir -p "${HOME}/.config/dein"
[ ! -d "${HOME}/.config/fish" ] && mkdir -p "${HOME}/.config/fish"
[ ! -d "${HOME}/.config/nvim" ] && mkdir -p "${HOME}/.config/nvim"
[ ! -d "${HOME}/.config/git" ] && mkdir -p "${HOME}/.config/git"
[ ! -d "${HOME}/.config/git/templates" ] && mkdir -p "${HOME}/.config/git/templates"
[ ! -d "${HOME}/.config/git/templates/hooks" ] && mkdir -p "${HOME}/.config/git/templates/hooks"
[ ! -d "${HOME}/.tmux" ] && mkdir -p "${HOME}/.tmux"
[ ! -d "${HOME}/.tmux/bin" ] && mkdir -p "${HOME}/.tmux/bin"

file_names=($(find ${DOTFILES_HOME} -name 'dot.*' -type f | awk -F/ '{print $NF}'))

for file_name in "${file_names[@]}"; do
  ln -fnsv "${DOTFILES_HOME}/${file_name}" "${HOME}/${file_name#dot}"
done

ln -fnsv "${DOTFILES_HOME}/dot.config/dein/plugins.toml" "${HOME}/.config/dein/plugins.toml"
ln -fnsv "${DOTFILES_HOME}/dot.config/dein/plugins_lazy.toml" "${HOME}/.config/dein/plugins_lazy.toml"
ln -fnsv "${DOTFILES_HOME}/dot.config/fish/config.fish" "${HOME}/.config/fish/config.fish"
ln -fnsv "${DOTFILES_HOME}/dot.config/fish/fishfile" "${HOME}/.config/fish/fishfile"
ln -fnsv "${DOTFILES_HOME}/dot.config/git/ignore" "${HOME}/.config/git/ignore"
ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/ctags" "${HOME}/.config/git/templates/hooks/ctags"
ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-checkout" "${HOME}/.config/git/templates/hooks/post-checkout"
ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-commit" "${HOME}/.config/git/templates/hooks/post-commit"
ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-merge" "${HOME}/.config/git/templates/hooks/post-merge"
ln -fnsv "${DOTFILES_HOME}/dot.config/nvim/init.vim" "${HOME}/.config/nvim/init.vim"
ln -fnsv "${DOTFILES_HOME}/dot.tmux/bin/reattach-to-user-namespace" "${HOME}/.tmux/bin/reattach-to-user-namespace"

echo "Installation has been completed."
