[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  colorscheme iceberg
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'wombat' }
'''

[[plugins]]
repo = 'janko/vim-test'
depends = ['vim-dispatch']
hook_add = '''
  let g:test#strategy = 'dispatch'
  nmap <Leader>tn :TestNearest<CR>
  nmap <Leader>tf :TestFile<CR>
  nmap <Leader>ts :TestSuite<CR>
  nmap <Leader>tl :TestLast<CR>
  nmap <Leader>tg :TestVisit<CR><Paste>
'''

[[plugins]]
repo = '/usr/local/opt/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  nnoremap <Leader>fb :Buffers<CR>
  nnoremap <Leader>fd :Files $HOME/ghq/github.com/ojiry/dotfiles<CR>
  nnoremap <Leader>ff :Files<CR>
  nnoremap <Leader>ft :Filetypes<CR>
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'
hook_add = '''
  nmap <silent> <Leader>gb :Gbrowse<CR>
  vmap <silent> <Leader>gb :Gbrowse<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
