[ftplugin]
elixir = '''
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
'''

python = '''
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4
'''

ruby = '''
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
'''

vim = '''
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
'''
