[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
  nmap <silent> <C-u><C-f> :<C-u>Denite file_rec<CR>
  nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
  nmap <silent> <C-u><C-l> :<C-u>Denite line<CR>
  nmap <silent> <C-u><C-w> :<C-u>DeniteCursorWord grep<CR>
  nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
'''
hook_post_source = '''
  call denite#custom#map('insert', '<C-n>',
    \ '<denite:move_to_next_line>')
  call denite#custom#map('insert', '<C-p>',
    \ '<denite:move_to_previous_line>')
  call denite#custom#map('_', '<C-s>',
    \ '<denite:do_action:split>')
  call denite#custom#map('insert', '<C-s>',
    \ '<denite:do_action:split>')
  call denite#custom#map('_', '<C-v>',
    \ '<denite:do_action:vsplit>')
  call denite#custom#map('insert', '<C-v>',
    \ '<denite:do_action:vsplit>')

  call denite#custom#var('file_rec', 'command',
    \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'default_opts',
    \ ['--vimgrep', '--no-heading'])
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']
