[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'kballard/vim-fish'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
