[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
