[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = 'ruby'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'Shougo/context_filetype.vim'
disabled = '!has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
on_i = 1
on_ft = 'snippet'
on_unite = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = [['n', '<Plug>']]

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'
