if &compatible
  set nocompatible
endif

function! s:source_rc(path) abort
  execute 'source' fnameescape(expand('~/.vim/rc/' . a:path))
endfunction

nnoremap ;  <Nop>
xnoremap ;  <Nop>
nnoremap m  <Nop>
xnoremap m  <Nop>
nnoremap ,  <Nop>
xnoremap ,  <Nop>

let $CACHE = expand('~/.cache')

let s:dein_dir = finddir('dein.vim', '.;')
if s:dein_dir != '' || &runtimepath !~ '/dein.vim'
  if s:dein_dir == '' && &runtimepath !~ '/dein.vim'
    let s:dein_dir = expand('$CACHE/dein')
          \. '/repos/github.com/Shougo/dein.vim'

    if !isdirectory(s:dein_dir)
      execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
    endif
  endif

  execute ' set runtimepath^=' . fnamemodify(s:dein_dir, ':p')
endif

call dein#begin(expand('$CACHE/dein'))

let s:toml_path = '~/.vim/rc/dein.toml'
let s:toml_lazy_path = '~/.vim/rc/deinlazy.toml'

if dein#load_cache([expand('<sfile>'), s:toml_path, s:toml_lazy_path])
  call dein#load_toml(s:toml_path, {'lazy': 0})
  call dein#load_toml(s:toml_lazy_path, {'lazy' : 1})
  call dein#save_cache()
endif

call s:source_rc('plugins.rc.vim')

call dein#end()

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on

syntax enable

set ambiwidth=double
set autoindent
set backspace=2
set clipboard+=unnamed
set cursorline
set encoding=utf-8
set expandtab
set hlsearch
set ignorecase
set laststatus=2
set nobackup
set number
set shiftwidth=2
set smartcase
set softtabstop=2
set wildmenu

hi Comment ctermfg=69

nnoremap <ESC><ESC> :nohlsearch<CR>:match<CR>

" TODO
au BufRead,BufNewFile,BufReadPre *.coffee set filetype=coffee

if filereadable(expand($HOME.'/.vimrc.local'))
  execute 'source' expand($HOME.'/.vimrc.local')
endif
