if &compatible
  set nocompatible
endif

function! s:source_rc(path) abort
  execute 'source' fnameescape(expand('~/.vim/rc/' . a:path))
endfunction

nnoremap ;  <Nop>
xnoremap ;  <Nop>
nnoremap m  <Nop>
xnoremap m  <Nop>
nnoremap ,  <Nop>
xnoremap ,  <Nop>

let $CACHE = expand('~/.cache')

let s:dein_dir = finddir('dein.vim', '.;')
if s:dein_dir != '' || &runtimepath !~ '/dein.vim'
  if s:dein_dir == '' && &runtimepath !~ '/dein.vim'
    let s:dein_dir = expand('$CACHE/dein')
          \. '/repos/github.com/Shougo/dein.vim'

    if !isdirectory(s:dein_dir)
      execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
    endif
  endif

  execute ' set runtimepath^=' . fnamemodify(s:dein_dir, ':p')
endif

call dein#begin(expand('$CACHE/dein'))

call dein#load_toml('~/.vim/rc/dein.toml', {'lazy': 0})

call s:source_rc('plugins.rc.vim')

call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on

syntax enable

set ambiwidth=double
set autoindent
set backspace=2
set clipboard+=unnamed
set cursorline
set encoding=utf-8
set expandtab
set hlsearch
set ignorecase
set laststatus=2
set nobackup
set number
set shiftwidth=2
set smartcase
set softtabstop=2
set wildmenu

hi Comment ctermfg=69

nnoremap <ESC><ESC> :nohlsearch<CR>:match<CR>
