[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

  [plugins.build]
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'vim-jp/autofmt'
