[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
  let g:memolist_path = expand('$HOME/Documents/Notes')
  let g:memolist_denite = 1
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'wombat' }
'''

[[plugins]]
repo = 'jodosha/vim-godebug'
hook_add = '''
  nnoremap [godebug] <Nop>
  nmap <Space>g [godebug]
  nmap <silent> [godebug]d :GoDebug<CR>
  nmap <silent> [godebug]t :GoToggleBreakpoint<CR>
'''

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'kballard/vim-fish'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'mustache/vim-mustache-handlebars'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'ojiry/bolero.vim'
hook_add = '''
  colorscheme bolero
'''

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'
hook_add = '''
  nmap <silent> gb :Gbrowse<CR>
  vmap <silent> gb :Gbrowse<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_linters = {
    \ 'javascript': ['prettier', 'eslint'],
    \ 'ruby': [],
    \ }
'''
