#!/usr/bin/env bash

set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

if [ ! -n "$DOTFILES_HOME" ]; then
  DOTFILES_HOME="${HOME}/.dotfiles"
fi

file_names=($(find ${DOTFILES_HOME} -name 'dot.*' -type f | awk -F/ '{print $NF}'))

for file_name in "${file_names[@]}"; do
  if [ -n "$DOTFILE_DEBUG" ]; then
    echo ${file_name}
  else
    ln -fnsv "${DOTFILES_HOME}/${file_name}" "${HOME}/${file_name#dot}"
  fi
done

if [ -n "$DOTFILE_DEBUG" ]; then
  echo '.config/dein/plugins.toml'
  echo '.config/dein/plugins_lazy.toml'
  echo '.config/fish/config.fish'
  echo '.config/fish/fishfile'
  echo '.config/git/ignore'
  echo '.config/git/templates/hooks/ctags'
  echo '.config/git/templates/hooks/post-checkout'
  echo '.config/git/templates/hooks/post-commit'
  echo '.config/git/templates/hooks/post-merge'
  echo '.config/nvim/init.vim'
  echo '.tmux/bin/reattach-to-user-namespace'
else
  ln -fnsv "${DOTFILES_HOME}/dot.config/dein/plugins.toml" "${HOME}/.config/dein/plugins.toml"
  ln -fnsv "${DOTFILES_HOME}/dot.config/dein/plugins_lazy.toml" "${HOME}/.config/dein/plugins_lazy.toml"
  ln -fnsv "${DOTFILES_HOME}/dot.config/fish/config.fish" "${HOME}/.config/fish/config.fish"
  ln -fnsv "${DOTFILES_HOME}/dot.config/fish/fishfile" "${HOME}/.config/fish/fishfile"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/ignore" "${HOME}/.config/git/ignore"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/ctags" "${HOME}/.config/git/templates/hooks/ctags"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-checkout" "${HOME}/.config/git/templates/hooks/post-checkout"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-commit" "${HOME}/.config/git/templates/hooks/post-commit"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/templates/hooks/post-merge" "${HOME}/.config/git/templates/hooks/post-merge"
  ln -fnsv "${DOTFILES_HOME}/dot.config/nvim/init.vim" "${HOME}/.config/nvim/init.vim"
  ln -fnsv "${DOTFILES_HOME}/dot.tmux/bin/reattach-to-user-namespace" "${HOME}/.tmux/bin/reattach-to-user-namespace"
fi
