#!/usr/bin/env bash

set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

if [ ! -n "$DOTFILES_HOME" ]; then
  DOTFILES_HOME="${HOME}/.dotfiles"
fi

file_names=($(find ${DOTFILES_HOME} -name 'dot.*' -type f | awk -F/ '{print $NF}'))

for file_name in "${file_names[@]}"; do
  if [ -n "$DOTFILE_DEBUG" ]; then
    echo ${file_name}
  else
    ln -fnsv "${DOTFILES_HOME}/${file_name}" "${HOME}/${file_name#dot}"
  fi
done

if [ -n "$DOTFILE_DEBUG" ]; then
  echo '.config/fish/config.fish'
  echo '.config/fish/fishfile'
  echo '.config/git/ignore'
  echo '.config/nvim/init.vim'
  echo '.vim/filetype.vim'
  echo '.vim/ftplugin'
  echo '.vim/rc'
else
  ln -fnsv "${DOTFILES_HOME}/dot.config/fish/config.fish" "${HOME}/.config/fish/config.fish"
  ln -fnsv "${DOTFILES_HOME}/dot.config/fish/fishfile" "${HOME}/.config/fish/fishfile"
  ln -fnsv "${DOTFILES_HOME}/dot.config/git/ignore" "${HOME}/.config/git/ignore"
  ln -fnsv "${DOTFILES_HOME}/dot.vim/init.vim" "${HOME}/.config/nvim/init.vim"
  ln -fnsv "${DOTFILES_HOME}/dot.vim/filetype.vim" "${HOME}/.vim/filetype.vim"
  ln -fnsv "${DOTFILES_HOME}/dot.vim/ftplugin" "${HOME}/.vim/ftplugin"
  ln -fnsv "${DOTFILES_HOME}/dot.vim/rc" "${HOME}/.vim/rc"
fi
