#!/usr/bin/env bash

set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

[ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
[ ! -d "${HOME}/.config/fish" ] && mkdir -p "${HOME}/.config/fish"
[ ! -d "${HOME}/.config/nvim" ] && mkdir -p "${HOME}/.config/nvim"
[ ! -d "${HOME}/.config/git" ] && mkdir -p "${HOME}/.config/git"
[ ! -d "${HOME}/.vim" ] && mkdir -p "${HOME}/.vim"
