#!/usr/bin/env bash

set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

[ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
[ ! -d "${HOME}/.config/dein" ] && mkdir -p "${HOME}/.config/dein"
[ ! -d "${HOME}/.config/fish" ] && mkdir -p "${HOME}/.config/fish"
[ ! -d "${HOME}/.config/nvim" ] && mkdir -p "${HOME}/.config/nvim"
[ ! -d "${HOME}/.config/git" ] && mkdir -p "${HOME}/.config/git"
[ ! -d "${HOME}/.config/git/templates" ] && mkdir -p "${HOME}/.config/git/templates"
[ ! -d "${HOME}/.config/git/templates/hooks" ] && mkdir -p "${HOME}/.config/git/templates/hooks"
[ ! -d "${HOME}/.tmux" ] && mkdir -p "${HOME}/.tmux"
[ ! -d "${HOME}/.tmux/bin" ] && mkdir -p "${HOME}/.tmux/bin"
