#!/usr/bin/env bash

set -e

if [ "$1" = "--debug" ]; then
  export DOTFILE_DEBUG=1
  shift
fi

if [ -n "$DOTFILE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

if [ ! -n "$DOTFILES_HOME" ]; then
  DOTFILES_HOME="${HOME}/.dotfiles"
fi

file_names=($(find ${DOTFILES_HOME} -name 'dot.*' -type f))

echo 'hoge'
echo $file_names

for file_name in "${file_names[@]}"; do
  if [ -n "$DOTFILE_DEBUG" ]; then
    echo ${file_name}
    echo 'hoge'
  else
    ln -fnsv "${DOTFILES_DIR}/${file_name}" "${HOME}/.${file_name}"
  fi
done

# [ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
# [ ! -d "${HOME}/.config/fish" ] && mkdir -p "${HOME}/.config/fish"
# [ ! -d "${HOME}/.vim" ] && mkdir -p "${HOME}/.vim"
# 
# if [ -n "$DOTFILE_DEBUG" ]; then
#   
# else
#   ln -fnsv "${DOTFILES_DIR}/dot.config/fish/config.fish/" "${HOME}/.config/fish/config.fish"
#   ln -fnsv "${HOME}/.vim/" "${HOME}/.config/nvim"
# fi
